<?php

namespace ShopBundle\Repository;

/**
 * Commande_detailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Commande_detailRepository extends \Doctrine\ORM\EntityRepository
{
}
