<?php

namespace ShopBundle\Repository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
    function updateDQL($id,$prix)
    {
        $query = $this->getEntityManager()
            ->createQuery("update ShopBundle:Commande c set c.nbProduit=c.nbProduit+1,c.prix=c.prix+:a WHERE c.idClient=:n ")
            ->setParameter('n', $id)->setParameter('a',$prix);
        return $query->getResult();
    }
}
