<?php

namespace ShopBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    function updateDQL($id){
        $query=$this->getEntityManager()
            ->createQuery("update ShopBundle:Produit p set p.nbVente=p.nbVente+1 WHERE p.id=:n ")
            ->setParameter('n',$id);
        return $query->getResult();
    }

    function update2DQL($id){
        $query=$this->getEntityManager()
            ->createQuery("update ShopBundle:Produit p set p.quantite=p.quantite-1 WHERE p.id=:n ")
            ->setParameter('n',$id);
        return $query->getResult();
    }

    function stat1DQL(){
        $query=$this->getEntityManager()
            ->createQuery("select sum(p.quantite) from ShopBundle:Produit p");
        return $query->getResult();
    }

    function stat2DQL(){
        $query=$this->getEntityManager()
            ->createQuery("select sum(p.quantite*p.prix) from ShopBundle:Produit p");
        return $query->getResult();
    }
    function stat3DQL(){
        $query=$this->getEntityManager()
            ->createQuery("select sum(p.prix) from ShopBundle:Commande p");
        return $query->getResult();
    }
    function stat4DQL(){
        $query=$this->getEntityManager()
            ->createQuery("select count(p.id) from ShopBundle:Reclamation p where p.etat='undone'");
        return $query->getResult();
    }
    function FindByDQL($nom){
        $query=$this->getEntityManager()
            ->createQuery("select c from ShopBundle:Produit c where c.nom like :n order by c.id desc")
            ->setParameter('n',$nom.'%');
        return $query->getResult();
    }

}
