<?php

namespace ShopBundle\Repository;

/**
 * ReclamationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReclamationRepository extends \Doctrine\ORM\EntityRepository
{
    function update2DQL($id){
        $query=$this->getEntityManager()
            ->createQuery("update ShopBundle:Reclamation p set p.etat='treated' WHERE p.id=:n ")
            ->setParameter('n',$id);
        return $query->getResult();
    }
}
