<?php

namespace AuditionBundle\Repository;

/**
 * AuditionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuditionRepository extends \Doctrine\ORM\EntityRepository
{
    function stat4DQL(){
        $query=$this->getEntityManager()
            ->createQuery("select count(p.id) from AuditionBundle:Audition p where p.checked='0' ");
        return $query->getResult();
    }
}
