<?php

namespace EvenementBundle\Repository;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends \Doctrine\ORM\EntityRepository
{
    public function findItemsCreatedBetweenTwoDates(\DateTime $beginDate, \DateTime $endDate)
    {
        return $this->createQueryBuilder('m')
            ->where("m.date > 1")
            ->andWhere("m.date < 2")
            ->setParameter(1, $beginDate)
            ->setParameter(2, $endDate)
            ->getQuery()
            ->getResult();
    }
  /*  public function findAllOrderedByName($datedebut,$datefin)
    {*/
        /* return $this->getEntityManager()
             ->createQuery(
                 'SELECT p FROM EvenementBundle:Evenement p where (p.date = 15/06/2019) ORDER BY p.date ASC'
             )
             ->getResult();*/
        /*$date_from = new \DateTime('now');
         ->setParameter('date_from', $date_from)
         ->andWhere('e.datedeb > = :date_form')*/

        /*  $query = $this->getEntityManager()
              ->createQuery('SELECT p FROM EvenementBundle:Evenement p WHERE p.date> 15-02-2022 ' );
          return $query->getResult();*/

    /*    $query = $this->getEntityManager()
            ->createQuery(" 
    select s from EvenementBundle:Evenement s
    WHERE   s.date like :datedebut  or  s.date like :datefin 
      ")
            ->setParameter('datedebut', '%' . $datedebut . '%')->setParameter('datefin', '%' . $datefin . '%');
        return $query->getResult();
    }*/
    public function findAllOrderedByName($datedebut,$datefin)
    {
        $query = $this->getEntityManager()
            ->createQuery(" 
    select s from EvenementBundle:Evenement s 
    WHERE   s.date like :datedebut  or  s.date like :datefin 
      ")
            ->setParameter('datedebut', '%' . $datedebut . '%')->setParameter('datefin', '%' . $datefin . '%');
        return $query->getResult();
    }


}
