<?php

namespace EvenementBundle\Repository;

/**
 * ParticipationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTotal($id)
    {
        /*$qb = $this->createQueryBuilder('a')
            ->join('a.user_id', 'c')
            ->addSelect('c')
            ->where('c.user_id = :id')
            ->setParameter('id', $id)
            ->getQuery();
        return (int)count($qb->getResult());*/
        $query = $this->createQueryBuilder('c')
            ->addSelect('s')
            ->leftJoin('c.user_id', 's')
            ->orderBy('c.dateParticipation')
            ->getQuery();

        return $query->getResult();
    }

    public function findAllWithCalculus($idu)
    {
        return $this->createQueryBuilder('m')
            ->where('m.user_id = :idu')
            ->setParameter('idu', $idu)
            ->getQuery()
            ->getArrayResult()
            ;
    }

}
