<?php

namespace ChatBundle\Repository;

/**
 * ConversationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConversationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUsereconv($id)
    {
        $query = $this->getEntityManager()->createQuery(
            "SELECT A FROM ChatBundle:Conversation A WHERE A.id = :id")
            ->setParameter( 'id',$id);


        return $query->getResult();

    }


    public function findByUsers($userId)
    {

        $query = $this->createQueryBuilder('t')
            ->leftJoin('t.users', 'm')
            ->where('m.id = :idUser')
            ->setParameter('idUser', $userId)
            ->getQuery();



        return $query->getResult();

    }

}
