<?php

namespace PublicationBundle\Repository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{

    function findCommentaire($id)
    {

        $query = $this->getEntityManager()
            ->createQuery("
         select C from PublicationBundle:Commentaire C 
         where C.id_publication = :id")
            ->setParameter('id', $id);
        return $query->getResult();
    }

}