<?php

namespace PublicationBundle\Repository;

/**
 * PublicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationRepository extends \Doctrine\ORM\EntityRepository
{
    function findPublication($id)
    {

        $query = $this->getEntityManager()
            ->createQuery("
         select P from PublicationBundle:Publication P
         where P.id = :id")
            ->setParameter('id', $id);
        return $query->getResult();
    }

    function FindByDQL($nom)
    {
        $query=$this->getEntityManager()
            ->createQuery("
            select p from PublicationBundle:Publication p
            where p.description like :n order by p.id desc
            ")
            ->setParameter('n','%'.$nom.'%');
        return $query->getResult();
    }

    function trieDQL(){
        $query=$this->getEntityManager()
            ->createQuery("select p from PublicationBundle:Publication p order by ");
        return $query->getResult();
    }

    function update2DQL($id){
        $query=$this->getEntityManager()
            ->createQuery("update PublicationBundle:Publication p set p.like=p.like+1 WHERE p.id=:n ")
            ->setParameter('n',$id);
        return $query->getResult();
    }
}
